# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://localhost:8080
gitlocation: https://github.com/jaypowley/FsBlog.git
gitbranch: master
title: FsBlog
description: Add something here
source: ../BlogContent/
blog: ../BlogContent/blog/
blogIndex: ../BlogContent/blog/index.cshtml
beers: ../BlogContent/beer/
beerIndex: ../BlogContent/beer/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: ../Output/
deploy: deploy
themes: themes