# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jasonpowley.com
gitlocation: https://github.com/jaypowley/FsBlog.git
gitbranch: master
title: JasonPowley.com
description: A blog of beer and code
source: C:\Users\Jason\Documents\BlogSource/
blog: C:\Users\Jason\Documents\BlogSource/blog/
blogIndex: C:\Users\Jason\Documents\BlogSource/blog/index.cshtml
beers: C:\Users\Jason\Documents\BlogSource/beer/
beerIndex: C:\Users\Jason\Documents\BlogSource/beer/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: ../Output/
deploy: deploy
themes: themes